export const indianCities = [
  // Major cities for general reach
  "Ahmedabad", "Bengaluru", "Chennai", "Delhi", "Hyderabad", "Kolkata", "Mumbai",
  "Pune", "Surat", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore",

  // Bangalore and its neighborhoods, suburbs, and nearby towns
  "Whitefield", "Electronic City", "Koramangala", "Indiranagar", "BTM Layout", "HSR Layout",
  "Jayanagar", "Rajajinagar", "Basavanagudi", "Banashankari", "Bannerghatta", "Hebbal",
  "Malleshwaram", "Marathahalli", "Yelahanka", "Kengeri", "Nagarbhavi", "JP Nagar",
  "Vijayanagar", "Hennur", "Kasturi Nagar", "KR Puram", "Majestic", "Shivajinagar",
  "Ulsoor", "RT Nagar", "Peenya", "Wilson Garden", "Domlur", "Fraser Town", "MG Road",
  "Richmond Town", "Cox Town", "Basaveshwaranagar", "Sadashivanagar", "Lavelle Road",
  "Vasanth Nagar", "Chamarajpet", "Magadi Road", "Padmanabhanagar", "Sanjay Nagar",
  "Seshadripuram", "Kammanahalli", "Hulimavu", "JP Nagar", "Arekere", "Devanahalli",
  "Doddaballapur", "Hoskote", "Nelamangala", "Ramanagara", "Anekal", "Attibele",
  "Sarjapur", "Begur", "Bagalur", "Jigani", "Harohalli", "Varthur", "Thindlu", "Nagawara",
  "Thanisandra", "Kaggadasapura", "Horamavu", "Banaswadi", "Mahadevpura", "Kodigehalli",
  "Yeshwanthpur", "Kumaraswamy Layout", "Banashankari Stage 2", "Bommanahalli",
  "Vidyaranyapura", "Hoodi", "Bel Circle", "Kadugodi", "CV Raman Nagar", "Sahakar Nagar",
  "Girinagar", "Varthur Kodi", "Sunkadakatte", "Anjanapura", "Konanakunte", "Kengeri Satellite Town",
  "Hesaraghatta", "Chikkaballapur", "Kolar", "Tumkur", "Doddanekkundi", "Bellandur",
  "Brookefield", "Jalahalli", "Tavarekere", "Rajarajeshwari Nagar", "Kudlu Gate",
  "Singsandra", "Ejipura", "Vignananagar", "Hoodi Circle", "Munnekolala", "KR Market",
  "Benson Town", "Nagavara", "Kundalahalli", "Kudlu", "Kanakapura Road", "Bannerghatta Road",
  "Old Madras Road", "Outer Ring Road", "Hosur Road", "Jalahalli East", "Srirampura",
  "Mico Layout", "Gottigere", "BTM 2nd Stage", "BTM 1st Stage", "Kathriguppe", "Nayandahalli",
  "Uttarahalli", "Kengeri Upanagara", "Jnanabharathi", "Bidadi", "Channapatna",
  "Malur", "Bangarpet", "Adugodi", "Kamakshipalya", "Sampangiram Nagar", "Jeevanbheema Nagar",
  "HAL Layout", "Rajbhavan Road", "Yeshwanthpur Industrial Area", "Bommasandra", "Vyalikaval",
  "Sarakki", "Nagasandra", "Manayata Tech Park", "Bhattarahalli", "Byrathi", "Kodathi", "Gunjur",
  "Seegehalli", "Basapura", "Medahalli", "Ananthnagar", "Ramamurthy Nagar", "Vijinapura",
  "Kithaganur", "Tindlu", "Arakere", "Kacharakanahalli", "Begur Road", "Somasundarapalya",
  "Akshayanagar", "Muneshwara Nagar", "JP Nagar Phase 7", "Hulimangala", "Madiwala", "Choodasandra",
  "Chikka Tirupathi", "Muthanallur", "Dommasandra", "Channasandra", "Ambalipura", "Harlur", "Basavanapura",


    "Ahmedabad", "Amritsar", "Agra", "Ajmer", "Allahabad", "Aligarh", "Alwar", "Ambala",
  "Aurangabad", "Asansol", "Bareilly", "Bengaluru", "Bhopal", "Bhubaneswar", "Bilaspur",
  "Bikaner", "Chandigarh", "Chennai", "Coimbatore", "Cuttack", "Dhanbad", "Dehradun",
  "Delhi", "Durgapur", "Ernakulam", "Erode", "Faridabad", "Firozabad", "Gandhinagar",
  "Ghaziabad", "Gorakhpur", "Guntur", "Guwahati", "Gwalior", "Haldwani", "Haridwar",
  "Hazaribagh", "Hisar", "Hosur", "Hubli", "Hyderabad", "Imphal", "Indore", "Itanagar",
  "Jabalpur", "Jaipur", "Jalandhar", "Jalgaon", "Jammu", "Jamnagar", "Jamshedpur",
  "Jhansi", "Jodhpur", "Junagadh", "Kakinada", "Kalaburagi", "Kalyan", "Kannur", "Kanpur",
  "Karnal", "Karur", "Kharagpur", "Kolhapur", "Kolkata", "Kollam", "Kota", "Kottayam",
  "Kozhikode", "Kurnool", "Latur", "Lucknow", "Ludhiana", "Madurai", "Mangalore",
  "Mathura", "Meerut", "Moradabad", "Muzaffarnagar", "Muzaffarpur", "Mysuru", "Nagpur",
  "Nanded", "Nashik", "Navi Mumbai", "Nellore", "Noida", "Palakkad", "Panaji", "Panipat",
  "Parbhani", "Patiala", "Patna", "Pondicherry", "Prayagraj", "Puducherry", "Pune",
  "Puri", "Raipur", "Rajahmundry", "Rajkot", "Ranchi", "Ratlam", "Rewa", "Rishikesh",
  "Rohtak", "Rourkela", "Sagar", "Saharanpur", "Salem", "Sambalpur", "Sangli", "Satna",
  "Secunderabad", "Shivpuri", "Shimla", "Shillong", "Sikar", "Silchar", "Siliguri",
  "Singrauli", "Sirsa", "Solapur", "Sonipat", "Srinagar", "Surat", "Thane", "Thrissur",
  "Tiruchirappalli", "Tirunelveli", "Tirupati", "Tiruppur", "Tiruvannamalai", "Trivandrum",
  "Tumkur", "Udaipur", "Ujjain", "Ulhasnagar", "Unnao", "Vadodara", "Valsad", "Varanasi",
  "Vasai", "Vellore", "Vijayawada", "Visakhapatnam", "Warangal", "Yamunanagar",
];
